### ISSUE TITLE
Instructions differ from code for .babelrc

### ISSUE THREAD

**Issue by OriginalPenguin** [krasimir/react-bare-minumum#4]
The code has the following .babelrc:

{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-env"
  ]
}

The instructions however say to use this:

{ "presets": ["react", "es2015"] }

Can you make them consistent so it's less confusing?  Also which is correct?

**Comment by fipo** [comment]
@OriginalPenguin :wave: 
the right one is that in `.babelrc`. I forgot to update the README.md ...

**Comment by krasimir** [comment]
Fixed. @OriginalPenguin good call.
